# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'invoiciz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1288, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
"height : 41;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(64, 64, 64);\n"
"border : 0px;\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius : 8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nav_frame = QtWidgets.QFrame(self.centralwidget)
        self.nav_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.nav_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.nav_frame.setStyleSheet("#nav_frame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom : 1px solid #404040;\n"
"}")
        self.nav_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nav_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nav_frame.setObjectName("nav_frame")
        self.frame_6 = QtWidgets.QFrame(self.nav_frame)
        self.frame_6.setGeometry(QtCore.QRect(20, 0, 671, 60))
        self.frame_6.setMinimumSize(QtCore.QSize(671, 60))
        self.frame_6.setMaximumSize(QtCore.QSize(671, 60))
        
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMinimumSize(QtCore.QSize(68, 21))
        self.label.setMaximumSize(QtCore.QSize(68, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #9747FF;\n"
"font-family: Roboto;\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.line_4 = QtWidgets.QFrame(self.frame_6)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.frame = QtWidgets.QFrame(self.frame_6)
        self.frame.setMaximumSize(QtCore.QSize(900, 34))
        
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(".QPushButton{\n"
"color: #FFF;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"border-radius: 8px;\n"
"background: #9747FF;\n"
 
"padding: 10px;\n"



"}\n"
"\n"
".QPushButton::hover {\n"
"background-color: rgb(94, 44, 159);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setStyleSheet(".QPushButton{\n"
 
"padding: 10px;\n"



"\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"color : #000;\n"
"border-bottom : 1px solid #000;\n"
"border-radius : 0px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setStyleSheet(".QPushButton{\n"
 
"padding: 10px;\n"



"\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"color : #000;\n"
"border-bottom : 1px solid #000;\n"
"border-radius : 0px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setStyleSheet(".QPushButton{\n"
 
"padding: 10px;\n"



"\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"color : #000;\n"
"border-bottom : 1px solid #000;\n"
"border-radius : 0px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setStyleSheet(".QPushButton{\n"
 
"padding: 10px;\n"



"\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"color : #000;\n"
"border-bottom : 1px solid #000;\n"
"border-radius : 0px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.nav_frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stacked = QtWidgets.QStackedWidget(self.main_frame)
        self.stacked.setObjectName("stacked")
        self.dashboard_page = QtWidgets.QWidget()
        self.dashboard_page.setObjectName("dashboard_page")
        self.frame_2 = QtWidgets.QFrame(self.dashboard_page)
        self.frame_2.setGeometry(QtCore.QRect(60, 50, 190, 97))
        self.frame_2.setMinimumSize(QtCore.QSize(190, 97))
        self.frame_2.setMaximumSize(QtCore.QSize(190, 97))
        self.frame_2.setStyleSheet("width: 190px;\n"
"height: 97px;\n"
  
"border-radius: 16px;\n"
"background: #9747FF;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.dashboard_page)
        self.frame_3.setGeometry(QtCore.QRect(280, 50, 190, 97))
        self.frame_3.setMinimumSize(QtCore.QSize(190, 97))
        self.frame_3.setMaximumSize(QtCore.QSize(190, 97))
        self.frame_3.setStyleSheet("width: 190px;\n"
"height: 97px;\n"
  
"border-radius: 16px;\n"
"background: #EEE;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.dashboard_page)
        self.frame_4.setGeometry(QtCore.QRect(500, 50, 190, 97))
        self.frame_4.setMinimumSize(QtCore.QSize(190, 97))
        self.frame_4.setMaximumSize(QtCore.QSize(190, 97))
        self.frame_4.setStyleSheet("width: 190px;\n"
"height: 97px;\n"
  
"border-radius: 16px;\n"
"background: #EEE;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.dashboard_page)
        self.frame_5.setGeometry(QtCore.QRect(720, 50, 190, 97))
        self.frame_5.setMinimumSize(QtCore.QSize(190, 97))
        self.frame_5.setMaximumSize(QtCore.QSize(190, 97))
        self.frame_5.setStyleSheet("width: 190px;\n"
"height: 97px;\n"
  
"border-radius: 16px;\n"
"background: #EEE;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_7 = QtWidgets.QFrame(self.dashboard_page)
        self.frame_7.setGeometry(QtCore.QRect(940, 50, 190, 97))
        self.frame_7.setMinimumSize(QtCore.QSize(190, 97))
        self.frame_7.setMaximumSize(QtCore.QSize(190, 97))
        self.frame_7.setStyleSheet("width: 190px;\n"
"height: 97px;\n"
  
"border-radius: 16px;\n"
"background: #EEE;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.stacked.addWidget(self.dashboard_page)
        self.invoices_page = QtWidgets.QWidget()
        self.invoices_page.setObjectName("invoices_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.invoices_page)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.invoices_page)
        self.label_5.setMaximumSize(QtCore.QSize(127, 16777215))
        self.label_5.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.invoices_page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.invoices_page)
        self.label_13.setMinimumSize(QtCore.QSize(20, 20))
        self.label_13.setMaximumSize(QtCore.QSize(92, 29))
        self.label_13.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.companyName_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.companyName_input.sizePolicy().hasHeightForWidth())
        self.companyName_input.setSizePolicy(sizePolicy)
        self.companyName_input.setMinimumSize(QtCore.QSize(20, 20))
        self.companyName_input.setMaximumSize(QtCore.QSize(247, 29))
        self.companyName_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.companyName_input.setObjectName("companyName_input")
        self.horizontalLayout_5.addWidget(self.companyName_input)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.invoices_page)
        self.label_19.setMinimumSize(QtCore.QSize(20, 20))
        self.label_19.setMaximumSize(QtCore.QSize(50, 29))
        self.label_19.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.companyPhone_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.companyPhone_input.sizePolicy().hasHeightForWidth())
        self.companyPhone_input.setSizePolicy(sizePolicy)
        self.companyPhone_input.setMinimumSize(QtCore.QSize(20, 20))
        self.companyPhone_input.setMaximumSize(QtCore.QSize(247, 29))
        self.companyPhone_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.companyPhone_input.setObjectName("companyPhone_input")
        self.horizontalLayout_6.addWidget(self.companyPhone_input)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.invoices_page)
        self.label_20.setMinimumSize(QtCore.QSize(20, 20))
        self.label_20.setMaximumSize(QtCore.QSize(50, 29))
        self.label_20.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.companyAddress_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.companyAddress_input.sizePolicy().hasHeightForWidth())
        self.companyAddress_input.setSizePolicy(sizePolicy)
        self.companyAddress_input.setMinimumSize(QtCore.QSize(20, 20))
        self.companyAddress_input.setMaximumSize(QtCore.QSize(247, 29))
        self.companyAddress_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.companyAddress_input.setObjectName("companyAddress_input")
        self.horizontalLayout_7.addWidget(self.companyAddress_input)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        self.type_comboBox = QtWidgets.QComboBox(self.invoices_page)
        self.type_comboBox.setMinimumSize(QtCore.QSize(247, 29))
        self.type_comboBox.setMaximumSize(QtCore.QSize(247, 29))
        self.type_comboBox.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.type_comboBox.setObjectName("type_comboBox")
        self.horizontalLayout_11.addWidget(self.type_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.invoices_page)
        self.label_6.setMaximumSize(QtCore.QSize(118, 16777215))
        self.label_6.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame(self.invoices_page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.invoices_page)
        self.label_14.setMinimumSize(QtCore.QSize(20, 20))
        self.label_14.setMaximumSize(QtCore.QSize(92, 29))
        self.label_14.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.productName_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.productName_input.sizePolicy().hasHeightForWidth())
        self.productName_input.setSizePolicy(sizePolicy)
        self.productName_input.setMinimumSize(QtCore.QSize(20, 20))
        self.productName_input.setMaximumSize(QtCore.QSize(247, 29))
        self.productName_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.productName_input.setObjectName("productName_input")
        self.horizontalLayout_10.addWidget(self.productName_input)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.invoices_page)
        self.label_21.setMinimumSize(QtCore.QSize(20, 20))
        self.label_21.setMaximumSize(QtCore.QSize(51, 29))
        self.label_21.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.productQuantity_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.productQuantity_input.sizePolicy().hasHeightForWidth())
        self.productQuantity_input.setSizePolicy(sizePolicy)
        self.productQuantity_input.setMinimumSize(QtCore.QSize(20, 20))
        self.productQuantity_input.setMaximumSize(QtCore.QSize(247, 29))
        self.productQuantity_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.productQuantity_input.setObjectName("productQuantity_input")
        self.horizontalLayout_8.addWidget(self.productQuantity_input)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_22 = QtWidgets.QLabel(self.invoices_page)
        self.label_22.setMinimumSize(QtCore.QSize(20, 20))
        self.label_22.setMaximumSize(QtCore.QSize(50, 29))
        self.label_22.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_9.addWidget(self.label_22)
        self.productPrice_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.productPrice_input.sizePolicy().hasHeightForWidth())
        self.productPrice_input.setSizePolicy(sizePolicy)
        self.productPrice_input.setMinimumSize(QtCore.QSize(20, 20))
        self.productPrice_input.setMaximumSize(QtCore.QSize(247, 29))
        self.productPrice_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.productPrice_input.setObjectName("productPrice_input")
        self.horizontalLayout_9.addWidget(self.productPrice_input)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.addButton = QtWidgets.QPushButton(self.invoices_page)
        self.addButton.setMinimumSize(QtCore.QSize(247, 29))
        self.addButton.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("color: #FFF;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"border-radius: 8px;\n"
"background: #9747FF;\n"
 
"padding: 10px;\n"


)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_12.addWidget(self.addButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.invoices_page)
        self.label_12.setMaximumSize(QtCore.QSize(247, 16777215))
        self.label_12.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.netPrice_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.netPrice_input.sizePolicy().hasHeightForWidth())
        self.netPrice_input.setSizePolicy(sizePolicy)
        self.netPrice_input.setMinimumSize(QtCore.QSize(247, 29))
        self.netPrice_input.setMaximumSize(QtCore.QSize(247, 29))
        self.netPrice_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.netPrice_input.setObjectName("netPrice_input")
        self.verticalLayout_3.addWidget(self.netPrice_input)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.invoices_page)
        self.label_11.setMaximumSize(QtCore.QSize(247, 16777215))
        self.label_11.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.discount_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.discount_input.sizePolicy().hasHeightForWidth())
        self.discount_input.setSizePolicy(sizePolicy)
        self.discount_input.setMinimumSize(QtCore.QSize(247, 29))
        self.discount_input.setMaximumSize(QtCore.QSize(247, 29))
        self.discount_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.discount_input.setObjectName("discount_input")
        self.verticalLayout_4.addWidget(self.discount_input)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.invoices_page)
        self.label_10.setMaximumSize(QtCore.QSize(247, 16777215))
        self.label_10.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.totalPrice_input = QtWidgets.QLineEdit(self.invoices_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.totalPrice_input.sizePolicy().hasHeightForWidth())
        self.totalPrice_input.setSizePolicy(sizePolicy)
        self.totalPrice_input.setMinimumSize(QtCore.QSize(247, 29))
        self.totalPrice_input.setMaximumSize(QtCore.QSize(247, 29))
        self.totalPrice_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.totalPrice_input.setObjectName("totalPrice_input")
        self.verticalLayout_5.addWidget(self.totalPrice_input)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.saveInvoice_button = QtWidgets.QPushButton(self.invoices_page)
        self.saveInvoice_button.setMinimumSize(QtCore.QSize(247, 29))
        self.saveInvoice_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.saveInvoice_button.setFont(font)
        self.saveInvoice_button.setStyleSheet("#saveInvoice_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #0A9E5B;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#saveInvoice_button::hover{\n"
"background-color: #0A9E5B;\n"
"color: #fff;\n"
"}")
        self.saveInvoice_button.setObjectName("saveInvoice_button")
        self.verticalLayout_6.addWidget(self.saveInvoice_button)
        self.printInvoice_button = QtWidgets.QPushButton(self.invoices_page)
        self.printInvoice_button.setMinimumSize(QtCore.QSize(247, 29))
        self.printInvoice_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.printInvoice_button.setFont(font)
        self.printInvoice_button.setStyleSheet("#printInvoice_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #475CFF;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#printInvoice_button::hover{\n"
"background-color: #475CFF;\n"
"color: #fff;\n"
"}")
        self.printInvoice_button.setObjectName("printInvoice_button")
        self.verticalLayout_6.addWidget(self.printInvoice_button)
        self.cancelInvoice_button = QtWidgets.QPushButton(self.invoices_page)
        self.cancelInvoice_button.setMinimumSize(QtCore.QSize(247, 29))
        self.cancelInvoice_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.cancelInvoice_button.setFont(font)
        self.cancelInvoice_button.setStyleSheet("#cancelInvoice_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #FF0404;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#cancelInvoice_button::hover{\n"
"background-color: #FF0404;\n"
"color: #fff;\n"
"}")
        self.cancelInvoice_button.setObjectName("cancelInvoice_button")
        self.verticalLayout_6.addWidget(self.cancelInvoice_button)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.create_tableView = QtWidgets.QTableView(self.invoices_page)
        self.create_tableView.setMinimumSize(QtCore.QSize(971, 311))
        self.create_tableView.setObjectName("create_tableView")
        self.horizontalLayout_13.addWidget(self.create_tableView)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.label_5.raise_()
        self.line.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.netPrice_input.raise_()
        self.totalPrice_input.raise_()
        self.discount_input.raise_()
        self.create_tableView.raise_()
        self.label_6.raise_()
        self.line_2.raise_()
        self.saveInvoice_button.raise_()
        self.printInvoice_button.raise_()
        self.cancelInvoice_button.raise_()
        self.label_13.raise_()
        self.companyName_input.raise_()
        self.type_comboBox.raise_()
        self.addButton.raise_()
        self.stacked.addWidget(self.invoices_page)
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.history_page)
        self.gridLayout_3.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_3.setSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.history_page)
        self.label_23.setMinimumSize(QtCore.QSize(20, 20))
        self.label_23.setMaximumSize(QtCore.QSize(38, 29))
        self.label_23.setStyleSheet("width: 99px;\n"
"height: 10px;\n"
  
"color: #000;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.historyType_comboBox = QtWidgets.QComboBox(self.history_page)
        self.historyType_comboBox.setMinimumSize(QtCore.QSize(247, 29))
        self.historyType_comboBox.setMaximumSize(QtCore.QSize(247, 29))
        self.historyType_comboBox.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.historyType_comboBox.setObjectName("historyType_comboBox")
        self.horizontalLayout_14.addWidget(self.historyType_comboBox)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_14)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.historySearch_input = QtWidgets.QLineEdit(self.history_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.historySearch_input.sizePolicy().hasHeightForWidth())
        self.historySearch_input.setSizePolicy(sizePolicy)
        self.historySearch_input.setMinimumSize(QtCore.QSize(20, 20))
        self.historySearch_input.setMaximumSize(QtCore.QSize(247, 29))
        self.historySearch_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.historySearch_input.setObjectName("historySearch_input")
        self.horizontalLayout_15.addWidget(self.historySearch_input)
        self.historySearch_Button = QtWidgets.QPushButton(self.history_page)
        self.historySearch_Button.setMinimumSize(QtCore.QSize(40, 29))
        self.historySearch_Button.setMaximumSize(QtCore.QSize(80, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.historySearch_Button.setFont(font)
        self.historySearch_Button.setStyleSheet("color: #FFF;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"border-radius: 8px;\n"
"background: #9747FF;\n"
 
"padding: 10px;\n"


)
        self.historySearch_Button.setObjectName("historySearch_Button")
        self.horizontalLayout_15.addWidget(self.historySearch_Button)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.history_tableView = QtWidgets.QTableView(self.history_page)
        self.history_tableView.setObjectName("history_tableView")
        self.verticalLayout_10.addWidget(self.history_tableView)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.deleteInvoice_button = QtWidgets.QPushButton(self.history_page)
        self.deleteInvoice_button.setMinimumSize(QtCore.QSize(247, 29))
        self.deleteInvoice_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.deleteInvoice_button.setFont(font)
        self.deleteInvoice_button.setStyleSheet("#deleteInvoice_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #FF0404;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#deleteInvoice_button::hover{\n"
"background-color: #FF0404;\n"
"color: #fff;\n"
"}")
        self.deleteInvoice_button.setObjectName("deleteInvoice_button")
        self.horizontalLayout_17.addWidget(self.deleteInvoice_button)
        self.editInvoice_button = QtWidgets.QPushButton(self.history_page)
        self.editInvoice_button.setMinimumSize(QtCore.QSize(247, 29))
        self.editInvoice_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.editInvoice_button.setFont(font)
        self.editInvoice_button.setStyleSheet("#editInvoice_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #000;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#editInvoice_button::hover{\n"
"background-color: #000;\n"
"color: #fff;\n"
"}")
        self.editInvoice_button.setObjectName("editInvoice_button")
        self.horizontalLayout_17.addWidget(self.editInvoice_button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.stacked.addWidget(self.history_page)
        self.products_page = QtWidgets.QWidget()
        self.products_page.setObjectName("products_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.products_page)
        self.gridLayout_4.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_4.setSpacing(8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.productSearch_input = QtWidgets.QLineEdit(self.products_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.productSearch_input.sizePolicy().hasHeightForWidth())
        self.productSearch_input.setSizePolicy(sizePolicy)
        self.productSearch_input.setMinimumSize(QtCore.QSize(20, 20))
        self.productSearch_input.setMaximumSize(QtCore.QSize(247, 29))
        self.productSearch_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.productSearch_input.setObjectName("productSearch_input")
        self.horizontalLayout_20.addWidget(self.productSearch_input)
        self.productSearch_Button = QtWidgets.QPushButton(self.products_page)
        self.productSearch_Button.setMinimumSize(QtCore.QSize(40, 29))
        self.productSearch_Button.setMaximumSize(QtCore.QSize(80, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.productSearch_Button.setFont(font)
        self.productSearch_Button.setStyleSheet("color: #FFF;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"border-radius: 8px;\n"
"background: #9747FF;\n"
 
"padding: 10px;\n"


)
        self.productSearch_Button.setObjectName("productSearch_Button")
        self.horizontalLayout_20.addWidget(self.productSearch_Button)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.tableView_3 = QtWidgets.QTableView(self.products_page)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_11.addWidget(self.tableView_3)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.addProduct_button = QtWidgets.QPushButton(self.products_page)
        self.addProduct_button.setMinimumSize(QtCore.QSize(247, 29))
        self.addProduct_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.addProduct_button.setFont(font)
        self.addProduct_button.setStyleSheet("#addProduct_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"color: #fff;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"    background-color: rgb(151, 71, 255);\n"
"}\n"
"\n"
"#addProduct_button::hover{\n"
"background-color: rgb(94, 44, 159);\n"
"}")
        self.addProduct_button.setObjectName("addProduct_button")
        self.horizontalLayout_19.addWidget(self.addProduct_button)
        self.deleteProduct_button = QtWidgets.QPushButton(self.products_page)
        self.deleteProduct_button.setMinimumSize(QtCore.QSize(247, 29))
        self.deleteProduct_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.deleteProduct_button.setFont(font)
        self.deleteProduct_button.setStyleSheet("#deleteProduct_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #FF0404;\n"
"color: #FF0404;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#deleteProduct_button::hover{\n"
"background-color: #FF0404;\n"
"color: #fff;\n"
"}")
        self.deleteProduct_button.setObjectName("deleteProduct_button")
        self.horizontalLayout_19.addWidget(self.deleteProduct_button)
        self.editProduct_button = QtWidgets.QPushButton(self.products_page)
        self.editProduct_button.setMinimumSize(QtCore.QSize(247, 29))
        self.editProduct_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.editProduct_button.setFont(font)
        self.editProduct_button.setStyleSheet("#editProduct_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #000;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#editProduct_button::hover{\n"
"background-color: #000;\n"
"color: #fff;\n"
"}")
        self.editProduct_button.setObjectName("editProduct_button")
        self.horizontalLayout_19.addWidget(self.editProduct_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stacked.addWidget(self.products_page)
        self.customers_page = QtWidgets.QWidget()
        self.customers_page.setObjectName("customers_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.customers_page)
        self.gridLayout_5.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_5.setSpacing(8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.cutomersSearch_input = QtWidgets.QLineEdit(self.customers_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(247)
        sizePolicy.setVerticalStretch(29)
        sizePolicy.setHeightForWidth(self.cutomersSearch_input.sizePolicy().hasHeightForWidth())
        self.cutomersSearch_input.setSizePolicy(sizePolicy)
        self.cutomersSearch_input.setMinimumSize(QtCore.QSize(20, 20))
        self.cutomersSearch_input.setMaximumSize(QtCore.QSize(247, 29))
        self.cutomersSearch_input.setStyleSheet("width: 247px;\n"
"height: 29px;\n"
  
"border-radius: 8px;\n"
"border: 1px solid #404040;\n"
"background: #FFF;")
        self.cutomersSearch_input.setObjectName("cutomersSearch_input")
        self.horizontalLayout_22.addWidget(self.cutomersSearch_input)
        self.customersSearch_Button = QtWidgets.QPushButton(self.customers_page)
        self.customersSearch_Button.setMinimumSize(QtCore.QSize(40, 29))
        self.customersSearch_Button.setMaximumSize(QtCore.QSize(80, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.customersSearch_Button.setFont(font)
        self.customersSearch_Button.setStyleSheet("color: #FFF;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"border-radius: 8px;\n"
"background: #9747FF;\n"
 
"padding: 10px;\n"


)
        self.customersSearch_Button.setObjectName("customersSearch_Button")
        self.horizontalLayout_22.addWidget(self.customersSearch_Button)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.verticalLayout_12.addLayout(self.horizontalLayout_21)
        self.tableView_4 = QtWidgets.QTableView(self.customers_page)
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout_12.addWidget(self.tableView_4)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        self.addCustomer_button = QtWidgets.QPushButton(self.customers_page)
        self.addCustomer_button.setMinimumSize(QtCore.QSize(247, 29))
        self.addCustomer_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.addCustomer_button.setFont(font)
        self.addCustomer_button.setStyleSheet("#addCustomer_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"color: #fff;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"    background-color: rgb(151, 71, 255);\n"
"}\n"
"\n"
"#addCustomer_button::hover{\n"
"background-color: rgb(94, 44, 159);\n"
"}")
        self.addCustomer_button.setObjectName("addCustomer_button")
        self.horizontalLayout_23.addWidget(self.addCustomer_button)
        self.deleteCustomer_button = QtWidgets.QPushButton(self.customers_page)
        self.deleteCustomer_button.setMinimumSize(QtCore.QSize(247, 29))
        self.deleteCustomer_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.deleteCustomer_button.setFont(font)
        self.deleteCustomer_button.setStyleSheet("#deleteCustomer_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #FF0404;\n"
"color: #FF0404;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#deleteCustomer_button::hover{\n"
"background-color: #FF0404;\n"
"color: #fff;\n"
"}")
        self.deleteCustomer_button.setObjectName("deleteCustomer_button")
        self.horizontalLayout_23.addWidget(self.deleteCustomer_button)
        self.editCustomer_button = QtWidgets.QPushButton(self.customers_page)
        self.editCustomer_button.setMinimumSize(QtCore.QSize(247, 29))
        self.editCustomer_button.setMaximumSize(QtCore.QSize(247, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.editCustomer_button.setFont(font)
        self.editCustomer_button.setStyleSheet("#editCustomer_button{\n"
 
"width: 212px;\n"
"height: 28px;\n"



  
"border-radius: 8px;\n"
"border: 1px solid #000;\n"
"color: #404040;\n"
"font-family: Roboto;\n"
"font-size: 12px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#editCustomer_button::hover{\n"
"background-color: #000;\n"
"color: #fff;\n"
"}")
        self.editCustomer_button.setObjectName("editCustomer_button")
        self.horizontalLayout_23.addWidget(self.editCustomer_button)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.gridLayout_5.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.stacked.addWidget(self.customers_page)
        self.gridLayout.addWidget(self.stacked, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Invoiciz"))
        self.label.setText(_translate("MainWindow", "Invoiciz"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Create Invoice"))
        self.pushButton_3.setText(_translate("MainWindow", "History"))
        self.pushButton_4.setText(_translate("MainWindow", "Products"))
        self.pushButton_5.setText(_translate("MainWindow", "Customers"))
        self.label_5.setText(_translate("MainWindow", "Customer Informations"))
        self.label_13.setText(_translate("MainWindow", "Company Name :"))
        self.label_19.setText(_translate("MainWindow", "Phone :"))
        self.label_20.setText(_translate("MainWindow", "Address :"))
        self.label_6.setText(_translate("MainWindow", "Products Information"))
        self.label_14.setText(_translate("MainWindow", "Product Name :"))
        self.label_21.setText(_translate("MainWindow", "Quantity :"))
        self.label_22.setText(_translate("MainWindow", "Price :"))
        self.addButton.setText(_translate("MainWindow", "Add Product"))
        self.label_12.setText(_translate("MainWindow", "Net Price :"))
        self.label_11.setText(_translate("MainWindow", "Discount :"))
        self.label_10.setText(_translate("MainWindow", "Total Price :"))
        self.saveInvoice_button.setText(_translate("MainWindow", "Save Invoice"))
        self.printInvoice_button.setText(_translate("MainWindow", "Print Invoice"))
        self.cancelInvoice_button.setText(_translate("MainWindow", "Delete Invoice"))
        self.label_23.setText(_translate("MainWindow", "Type :"))
        self.historySearch_Button.setText(_translate("MainWindow", "Search"))
        self.deleteInvoice_button.setText(_translate("MainWindow", "Delete Invoice"))
        self.editInvoice_button.setText(_translate("MainWindow", "Edit Invoice"))
        self.productSearch_Button.setText(_translate("MainWindow", "Search"))
        self.addProduct_button.setText(_translate("MainWindow", "Add Product"))
        self.deleteProduct_button.setText(_translate("MainWindow", "Delete Product"))
        self.editProduct_button.setText(_translate("MainWindow", "Edit Product"))
        self.customersSearch_Button.setText(_translate("MainWindow", "Search"))
        self.addCustomer_button.setText(_translate("MainWindow", "Add Customer"))
        self.deleteCustomer_button.setText(_translate("MainWindow", "Delete Customer"))
        self.editCustomer_button.setText(_translate("MainWindow", "Edit Customer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
